### ISSUE TITLE
Question on requested permission READ_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by IzzySoft** [d4rken-org/sdmaid-se#956]
With my APK checker having been enhanced by additional checks, it just reported:

    ! repo/eu.darken.sdmse_1900000.apk declares risky permission(s): android.permission.READ_EXTERNAL_STORAGE

It also reported some other "sensitive permissions" where the use seemed clear to me, so I already added them to SDMSE's allow-list:

```yaml
      android.permission.MANAGE_EXTERNAL_STORAGE: The app’s purpose is to cleanup storage.
      android.permission.QUERY_ALL_PACKAGES: The app needs that to identify app-specific files.
      android.permission.REQUEST_DELETE_PACKAGES: The app needs this for its AppControl feature (to uninstall apps specified).
```

I'm no Android developer, so I'm not 100% sure: Is `READ_EXTERNAL_STORAGE` still needed despite an app already having `MANAGE_EXTERNAL_STORAGE`? According to [the documentation](https://developer.android.com/training/data-storage/manage-all-files), `MANAGE_EXTERNAL_STORAGE` already covers "Read and write access to all files within [shared storage](https://developer.android.com/training/data-storage/shared)."

Should it indeed be needed additionally, some background would be appreciated so I can add it to the other 3. Else, it might be not the worst idea to maybe remove it, I guess?

Thanks in advance!

PS: Corrections to my above descriptions are of course also welcome, where needed.
